#pragma once

#include "esp_event_base.h"

ESP_EVENT_DECLARE_BASE(MOISTURE_EVENTS);
ESP_EVENT_DEFINE_BASE(MOISTURE_EVENTS);
enum {
    MOISTURE_WIFI_AVAILABLE_EVENT,
    MOISTURE_STORAGE_AVAILABLE_EVENT,
    MOISTURE_MEASUREMENT_EVENT,
    MOISTURE_STORED_EVENT,
    MOISTURE_ERROR_EVENT
};

static esp_event_loop_handle_t moisture_eventloop;
